[default]
TITLE = "PyTradeGames"
SECRET_KEY = "24992a60806afb5a0ff52331347a9e126fef45ed43f66d8d2ec5818d6cf4736d"
EXTENSIONS = [
    'PyTradeGames.ext.database:init_app',
    'PyTradeGames.ext.database.migration:init_app',
    'PyTradeGames.ext.authentication:init_app',
    'PyTradeGames.ext.admin:init_app',
    'PyTradeGames.ext.cli:init_app',

    'PyTradeGames.blueprints.webui:init_app'
]
FLASK_ADMIN_SWATCH = 'sandstone'


[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///dev_database.db"